### ISSUE TITLE
메인화면 구현

### ISSUE THREAD

**Issue by notusing11** [jiphyeonjeon-42/frontend#10]
## description
> 디자인요소를 고려하여 메인 페이지를 구현합니다. 
## todo
- [x] 기본적인 골격 완성
- [x] 신작도서 페이지네이션 원들
- [x] 백엔드 api로 변경
- [x] 신작과 인기도서 상세페이지로 링크
- [x] 기타 디자인적 요소 검토
