### ISSUE TITLE
Header, Footer, Banner 컴포넌트 반응형

### ISSUE THREAD

**Issue by Jiwon-Woo** [jiphyeonjeon-42/frontend#108]
## description
> 공통으로 사용하는 컴포넌트인 Header, Footer, Banner 반응형으로 처리 (최소 너비 360)
## todo
- [x] Header
    - [x] 반응형에 대응하기 위해 컴포넌트 배치 변경
    - [x] 모바일용 헤더 컴포넌트 추가
- [x] Footer
    - [x] 모바일(360~768)은 레이아웃 변경
- [x] Banner
    - [x] BackGround와 Title을 대체할 Banner 컴포넌트 추가 및 반응형 대응
    - [x] Main 과 Search 페이지의 Banner는 따로
