### ISSUE TITLE
이용안내 페이지 폰트 사이즈 조정 및 전체 여닫이 토글 추가

### ISSUE THREAD

**Issue by keinn51** [jiphyeonjeon-42/frontend#118]
## description
> 이용안내 페이지의 폰트 사이즈와 간격을 조절하고 토글을 추가합니다
## todo
- [x] 폰트 사이즈 조정
- [x] title과 question 사이 간격 줄이기
- [x] 전체 여닫이 토글 추가
