### ISSUE TITLE
검색페이지 배너 높이 조정 및 기타 fix

### ISSUE THREAD

**Issue by Jiwon-Woo** [jiphyeonjeon-42/frontend#127]
## description
> 검색페이지 배너 높이 조정 및 자잘한 fix
## todo
- [ ] 검색페이지 배너 높이 조정
- [ ] 헤더 z-index 5로 상향
- [ ] 탭 1번을 스페이스 2번으로 수정
