### ISSUE TITLE
REFACTOR: 탭리스트, 페이지네이션 수정

### ISSUE THREAD

**Issue by notusing11** [jiphyeonjeon-42/frontend#259]
## description
> 어드민 탭, 어드민 페이지네이션이었던 컴포넌트를 범용적으로 변경합니다. 

## todo
- [x] 이름변경 "Admin" 표현 삭제
- [x] 하드코딩되어 있는 탭리스트 data/tablist.js에서 import하도록 수정
- [x] 페이지네이션 제일 끝으로 가는 기능 추가
