### ISSUE TITLE
REFACTOR: 서치바 리팩토링

### ISSUE THREAD

**Issue by notusing11** [jiphyeonjeon-42/frontend#263]
## description
> 검색창으로 사용되는 컴포넌트를 개선하고 통합합니다. 

## todo
- [ ] 디바운스 기능 도입 
- [ ] QR리더기 열기 버튼 추가
- [ ] 어드민 서치바, 검색용 서치바, 도서등록용 서치바의 통합
- [ ] 다른 페이지로 넘어갔을 때 이전 검색어 남는 문제 해결
- [ ] 서치바 컴포넌트와 함께 반복적으로 사용되는 중복코드 포함
