### ISSUE TITLE
REFACTOR: 모달 리팩토링

### ISSUE THREAD

**Issue by notusing11** [jiphyeonjeon-42/frontend#270]
## description
> 여러 형태의 모달을 통합해서 활용성을 높입니다
## todo
- [x] createPortal을 활용한 Modal 추가
- [x] ModalHeader, ModalFooter 추가
- [x] 기존 MiniModal + ModalContent 통합, 메세지만 띄우는 Dialog로 개편
- [x] 기존 MidModal 제거
