### ISSUE TITLE
검색페이지 코드 리팩토링

### ISSUE THREAD

**Issue by Jiwon-Woo** [jiphyeonjeon-42/frontend#35]
## description
> 9/30 멘토링에서 받은 코드 리뷰를 바탕으로 검색페이지 리팩토링을 진행합니다.
## todo
- 함수명을 정할 때 get과 fetch의 의미를 구분하기
    - [x] getBookList -> fetchBookList 로 변경
    - [x] BookDetail.js의 getData -> fetchData 로 변경
    - [x] MainPopular.js의 getData -> fetchData 로 변경
- 전역 state의 사용 줄이기 (현재 검색페이지에서는 searchWord 와 useSearchInput 만 recoil state로 남아 있음)
    - [x] fetchBookList를 Book.js 에서 Search.js 로 이동
    - [x] CategoryFilter / SortBy / Pagenation / Books 등과 같은 컴포넌트를 UI적인 측면을 중심으로 구현
    - [x] Search.js 내에서 지역적으로 state를 활용하고, 나머지는 컴포넌트의 속성으로 할당
- 선언적으로 코드 작성하기
    - [x] publishedAt의 데이터 형태를 변환하는 함수를 따로 빼기
    - [x] publishedAt의 데이터 형태를 변환하는 함수는 Books.js 보다 BookInfo.js에서 적용하기
    - [x] startCate에 따른 Category의 노출여부는 Category(자식)보다 CategoryFilter(부모)에서 적용하기
- url searchWord를 쿼리스트링으로 변경
    - [x] searchWord(queryString)을 쿼리스트링으로 변경하면서 match 대신 location을 활용
    - [x] 예외상황에 대비한 인코딩 및 디코딩 작업 필요
