### ISSUE TITLE
컴포넌트 폴더 구조 리팩토링

### ISSUE THREAD

**Issue by Jiwon-Woo** [jiphyeonjeon-42/frontend#38]
## description
> 컴포넌트 폴더 구조를 페이지 별로 구분
## todo
- [x] 컴포넌트 폴더 구조 분리 (현재 진행중인 공통 컴포넌트 Modal과 ModalSearchBar 제외)
- [x] 컴포넌트 폴더 구조 분리에 따른 import 경로 변경
- [x] 대출페이지 유저검색 일부 구현
