### ISSUE TITLE
예약 등록

### ISSUE THREAD

**Issue by notusing11** [jiphyeonjeon-42/frontend#42]
## description
> 특정 책에 대한 예약 대기 상태를 안내하고 사용자의 요청을 받아 새로운 예약을 등록한다.
## todo
- [x] 책 상세 페이지의 예약하기 버튼 개선 : 예약가능 상태에 따라 버튼 표시 색 및 동작 수정
- [x] 예약하기 버튼 클릭 시 로그인 상태 확인 및 비로그인시 리다이렉트
- [x] 공통 컴포넌트 구현 MiniModal
- [x] 현재 예약 대기자 노출 및 사용자 의사 재확인
- [x] 예약 등록 성공 시 순위에 따라 반납예정일 노출
- [x] 예약 등록 실패 오류 처리 1. 사용자의 예약 제한으로 인한 실패, 실패 사유 알림
- [x] 예약 등록 실패 오류 처리 2. 기타 POST api 실패 HTTP 401 대응
