### ISSUE TITLE
태그 상세 페이지 CSS 개선

### ISSUE THREAD

**Issue by chanhihi** [jiphyeonjeon-42/frontend#446]
### 기능 설명

- [x] 태그가 0개일 때, 보여지는 부분 제거
- [x] input focus 제거

```[tasklist]
### Tasks
- [ ] https://github.com/jiphyeonjeon-42/frontend/issues/412
- [ ] https://github.com/jiphyeonjeon-42/frontend/issues/459
```
