### ISSUE TITLE
콘솔 오류 해결

### ISSUE THREAD

**Issue by scarf005** [jiphyeonjeon-42/frontend#480]
### 기능 설명

![image](https://github.com/jiphyeonjeon-42/frontend/assets/54838975/87c1de9c-20e9-4f3e-aed1-47c9045a06bc)

`pnpm dev`로 실행시 콘솔창에서 뜨는 오류 해결
```[tasklist]
### Tasks
- [ ] `MainPopular`에 `key` 추가
- [x] `MainNewBookList`에 `key` 추가
- [ ] https://github.com/jiphyeonjeon-42/frontend/issues/481
- [x] `index.tsx`로 전환
```
