### ISSUE TITLE
검색 상세 페이지 및 카테고리 필터

### ISSUE THREAD

**Issue by kth2624** [jiphyeonjeon-42/frontend#5]
## description
> 검색 상세페이지 구현 및 카테고리 필터
## todo
- [x] BookDetail 컴포넌트 구현
- [ ] BookStatus 컴포넌트 구현
- [ ] BookReservation 컴포넌트 구현
- [x] 컴포넌트 배치 프로토타입과 유사하게
- [x] footer 컴포넌트 형태 잡아보기

**Comment by Jiwon-Woo** [comment]
디자인 변경으로 인해 이슈 close
