### ISSUE TITLE
검색 페이지 보강

### ISSUE THREAD

**Issue by Jiwon-Woo** [jiphyeonjeon-42/frontend#55]
## description
> 검색 페이지에서 피드백 받은 부분을 수정합니다.
## todo
- [x] 검색 시 querystring 예외처리
    - [x] string, page, category, sort의 디폴트값 설정
    - [x] page <= 0 이면, page를 1로, page > totalPage 이면 page를 마지막 페이지로 설정
    - [x] categoryIndex 범위를 벗어나면 전체로 설정
- [x] 자세히 보기 버튼의 범위를 BookInfo 컴포넌트로 확대
