### ISSUE TITLE
대출 페이지 및 검색페이지 리팩토링

### ISSUE THREAD

**Issue by Jiwon-Woo** [jiphyeonjeon-42/frontend#60]
## description
> 대출 페이지 및 검색페이지 리팩토링
## todo
- [x] Proptypes 추가
- [x] recoil atom 분리
- [x] api get 오류시 예외 처리
- [x] 대출 모달창 검색 시 page 번호와 page range를 초기화
- [x] 대출 post 요청시 보내는 데이터 형식 수정
