### ISSUE TITLE
상세 페이지 도서상태 숫자 변경

### ISSUE THREAD

**Issue by notusing11** [jiphyeonjeon-42/frontend#64]
## description
> book id로 노출되던 화면을 index로 변경
## todo
- [x] bookdetail에서 index 숫자 넘김
- [x] bookstatus에서 id 대신 index 노출
- [x] 예약하기 버튼 선택적 활성화되도록 수정
