### ISSUE TITLE
11월 1일 집현전회의 피드백 반영

### ISSUE THREAD

**Issue by notusing11** [jiphyeonjeon-42/frontend#68]
## description
> 11/1 집현전 회의때 들은 피드백을 반영합니다
## todo
- [ ] 신작도서 홀짝 hover동작 통일 
- [x] 인기도서 api 오류시 컴파일 에러 수정
- [x] 미니모달 바깥부분 클릭시 모달창 꺼지도록
- [x] 도서상세 페이지 예약 비활성화 텍스트 수정 "예약하기" -> "예약불가"

**Comment by notusing11** [comment]
신작도서 hover 동작은  프론트회의 결과 해당 피드백은 수정하지 않기로 결정하였습니다. 
- 동작이 더 단조로워지는 느낌
- 책 이미지 크기랑 화살표박스 크기가 맞지 않아 생기는 어색함이 있음
