### ISSUE TITLE
메인페이지 인기도서 리팩토링

### ISSUE THREAD

**Issue by notusing11** [jiphyeonjeon-42/frontend#72]
## description
> 메인화면 인기도서 부분의 코드를 기능 및 역할별로 분리했습니다
## todo
- [x] 전역 상태 지역화
- [x] 코드 기능별 분리
- [x] 반응형 레이아웃 변화 대응 html 순서변경
