### ISSUE TITLE
로그인 시 만료일 체크

### ISSUE THREAD

**Issue by notusing11** [jiphyeonjeon-42/frontend#88]
## description
> 백엔드 쿠키의 만료일자를 추측할 수 있도록 수정합니다. 처음 로그인 정보를 받아온 후 2주 동안은 쿠키가 유효하다고 간주합니다.
## todo
- [x] auth GET api 통신 성공시 현재 생성일자를 기록 
- [x] 로컬스토리지에서 사용자 정보를 업데이트 할 때 생성 후 14일이 지났는지 판단하는 조건 추가
- [x] 헤더에서도 14일 지났는지 판단해서 만료면 login 페이지로 리다이렉트
