### ISSUE TITLE
대출 페이지 유저 검색 및 책 검색 api 대응 및 오류메세지 제거

### ISSUE THREAD

**Issue by Jiwon-Woo** [jiphyeonjeon-42/frontend#93]
## description
> 대출 페이지 유저 검색 및 책 검색 api가 완성됨에 따라 임시데이터로 처리했던 부분을 실제 데이터로 대체합니다.
## todo
- [x] 유저 검색 임시 데이터를 실제 데이터로 교체
- [x] 책 검색 isLenderable 부분 교체
- [x] 대출 페이지 컴포넌트에 propTypes 추가
- [x] 대출 페이지에서 발생하는 오류메세지 제거
